parameters:
  - name: solutionPath
    displayName: Visual Studio Solution Path
    type: string

  - name: projectPath
    displayName: App CSProj File Path
    type: string

  - name: buildConfiguration
    displayName: Build Configuration Profile
    type: string
    default: 'Release'

  - name: version
    displayName: DotNet Version
    default: '6.x'

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: "Install .NET 6.x"
    inputs:
      version: ${{ parameters.version }}
      packageType: sdk

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      sdk: ${{ parameters.solutionPath }}
      command: 'restore'
      projects: ${{ parameters.solution }}

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      sdk: ${{ parameters.version }} 
      command: 'build'
      projects: ${{ parameters.solutionPath }}
      arguments: '--configuration ${{ parameters.buildConfiguration }}'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '${{ parameters.solutionPath }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      projects: '${{ parameters.project }}'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True
      publishWebProjects: False
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop