parameters:
  - name: solutionPath
    displayName: Visual Studio Solution Path
    type: string

  - name: projectPath
    displayName: App CSProj File Path
    type: string

  - name: buildConfiguration
    displayName: Build Configuration Profile
    type: string
    default: 'Release'

  - name: dotNetVersion
    displayName: DotNet Version
    default: '6.x'

  - name: serviceConnectionDev
    displayName: DevService Connection Name
    type: string

  - name: serviceConnectionSIT
    displayName: SIT Service Connection Name
    type: string

  - name: serviceConnectionUAT
    displayName: UAT Service Connection Name
    type: string

  - name: serviceConnectionPrd
    displayName: Production Service Connection Name
    type: string
    
  - name: functionAppNameDev
    displayName: Dev Function App Name
    type: string
    
  - name: functionAppNameSIT
    displayName: SIT Function App Name
    type: string
    
  - name: functionAppNameUAT
    displayName: UAT Function App Name
    type: string

  - name: functionAppNamePrd
    displayName: Production Function App Name
    type: string

  - name: functionAppUrlDev
    displayName: Dev Function App Url
    type: string
    
  - name: functionAppUrlSIT
    displayName: SIT Function App Url
    type: string
    
  - name: functionAppUrlUAT
    displayName: UAT FFunction App Url
    type: string

  - name: functionAppUrlPrd
    displayName: Production Function App Url
    type: string

  - name: adAppIdUriDev
    displayName: Dev AAD App Id Uri
    type: string

  - name: adAppIdUriSIT
    displayName: SIT AAD App Id Uri
    type: string

  - name: adAppIdUriUAT
    displayName: UAT AAD App Id Uri
    type: string

  - name: adAppIdUriPrd
    displayName: Production AAD App Id Uri
    type: string

  - name: runtimeStack
    displayName: Runtime Stacak
    type: string
    default: DOTNET|6.0

  - name: appSettings
    displayName: Application Settings
    type: string
    default: ''

  - name: postmanCollection
    displayName: Postman Collection File Path
    type: string
    default: ''

  - name: postmanArgsDev
    displayName: Dev Postman Extra Command Line Args
    type: string
    default: ''

  - name: postmanArgsSIT
    displayName: SIT Postman Extra Command Line Args
    type: string
    default: ''

  - name: postmanArgsUAT
    displayName: UAT Postman Extra Command Line Args
    type: string
    default: ''

  - name: postmanArgsPrd
    displayName: Production Postman Extra Command Line Args
    type: string
    default: ''

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
    - template: build-publish-dotnet.yaml
      parameters:
        solutionPath: ${{ parameters.solutionPath }}
        projectPath: ${{ parameters.projectPath }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        version: ${{ parameters.dotNetVersion }}

  - stage: DeployDEV
    displayName: 'Deploy App to Dev'
    dependsOn: BuildAndTest
    jobs:
    - template: deploy-az-function-app.yaml
      parameters:
        environmentName: DEV
        serviceConnection: ${{ parameters.serviceConnectionDev }}
        functionAppName: ${{ parameters.functionAppNameDev }}
        adAppIdUri: ${{ parameters.adAppIdUriDev }}
        runtimeStack: ${{ parameters.runtimeStack }}
        appSettings: ${{ parameters.appSettings }}
        postmanCollection: ${{ parameters.postmanCollection }}
        postmanArgs: ${{ parameters.postmanArgsDev }} --global-var URL=${{ parameters.functionAppUrlDev }}
        
  - stage: DeploySIT
    displayName: 'Deploy App to SIT'
    dependsOn: DeployDEV
    jobs:
    - template: deploy-az-function-app.yaml
      parameters:
        environmentName: SIT
        serviceConnection: ${{ parameters.serviceConnectionPrd }}
        functionAppName: ${{ parameters.functionAppNameSIT }}
        adAppIdUri: ${{ parameters.adAppIdUriSIT }}
        runtimeStack: ${{ parameters.runtimeStack }}
        appSettings: ${{ parameters.appSettings }}
        postmanCollection: ${{ parameters.postmanCollection }}
        postmanArgs: ${{ parameters.postmanArgsSIT }} --global-var URL=${{ parameters.functionAppUrlSIT }}

  - stage: DeployUAT
    displayName: 'Deploy App to UAT'
    dependsOn: DeploySIT
    jobs:
    - template: deploy-az-function-app.yaml
      parameters:
        environmentName: UAT
        serviceConnection: ${{ parameters.serviceConnectionUAT }}
        functionAppName: ${{ parameters.functionAppNameUAT }}
        adAppIdUri: ${{ parameters.adAppIdUriUAT }}
        runtimeStack: ${{ parameters.runtimeStack }}
        appSettings: ${{ parameters.appSettings }}
        postmanCollection: ${{ parameters.postmanCollection }}
        postmanArgs: ${{ parameters.postmanArgsUAT }} --global-var URL=${{ parameters.functionAppUrlUAT }}

  - stage: DeployPRD
    displayName: 'Deploy App to Production'
    dependsOn: DeployUAT
    jobs:
    - template: deploy-az-function-app.yaml
      parameters:
        environmentName: PRD
        serviceConnection: ${{ parameters.serviceConnectionPrd }}
        functionAppName: ${{ parameters.functionAppNamePrd }}
        adAppIdUri: ${{ parameters.adAppIdUriPrd }}
        runtimeStack: ${{ parameters.runtimeStack }}
        appSettings: ${{ parameters.appSettings }}
        postmanCollection: ${{ parameters.postmanCollection }}
        postmanArgs: ${{ parameters.postmanArgsPrd }} --global-var URL=${{ parameters.functionAppUrlPrd }}